# Numpy

In [2]:
import numpy as np

heights = [189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 182, 185, 191]
ages = [57, 61, 57, 57, 58, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52, 56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60, 62, 43, 55, 56, 61, 52, 69, 64, 46, 54, 47, 70]

heights_arr = np.array(heights)
ages_arr = np.array(ages)

heights_arr = heights_arr.reshape((45,1))
ages_arr = ages_arr.reshape((45,1))


height_age_arr = np.hstack((heights_arr, ages_arr))
#print(height_age_arr)
print(height_age_arr.shape)
print(height_age_arr[:3,])

(45, 2)
[[189  57]
 [170  61]
 [189  57]]


In [5]:
np.array(heights)

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178,
       182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177,
       185, 188, 188, 182, 185, 191])

In [21]:
arr = np.array(heights).reshape((45,1))[:5]
arr

array([[189],
       [170],
       [189],
       [163],
       [183]])

In [23]:
arr1 = np.array(heights).reshape((45,1))
np.hstack((arr1,arr1))[:5]

array([[189, 189],
       [170, 170],
       [189, 189],
       [163, 163],
       [183, 183]])

In [27]:
np.concatenate((arr,arr), axis=1)

array([[189, 189],
       [170, 170],
       [189, 189],
       [163, 163],
       [183, 183]])

## Operations

In [28]:
(np.array([1,2,3]))*0.5

array([0.5, 1. , 1.5])

In [30]:
((np.array([1,2,3]))*0.5).sum()

3.0

Comparisons returne True or False

In [37]:
arr = (np.array([1,2,3]))
arr

array([1, 2, 3])

In [38]:
arr_true = arr > 1

In [41]:
arr[arr_true]

array([2, 3])

## Test

In a matrix, or 2-d array X, the averages (or means) of the elements of rows is called row means.

Task
Given a 2D array, return the rowmeans.

Input Format
First line: two integers separated by spaces, the first indicates the rows of matrix X (n) and the second indicates the columns of X (p)
Next n lines: values of the row in X

Output Format
An numpy 1d array of values rounded to the second decimal.

```
2 2
1.5 1
2 2.9

Sample Output
[1.25 2.45]
```

In [90]:
## Test

import numpy as np

n, p = [int(x) for x in input().split()]

X = np.zeros((n,p))
arr = np.zeros((1,p))

for i in range(n):
    arr = [float(y) for y in input().split()]
    X[i,:] = arr
    
print(X)
print(np.around(X.mean(axis=1),2))

[[4.566  6.544 ]
 [2.166  6.9494]]
[5.56 4.56]


---

# Pandas

In [98]:
import pandas as pd

presidents_df = pd.read_csv('https://sololearn.com/uploads/files/president_heights_party.csv', index_col='name')
                                  
print(presidents_df.groupby('party').mean())

                           order        age      height
party                                                  
democratic             26.066667  52.600000  181.066667
democratic-republican   4.500000  57.250000  176.500000
federalist              2.000000  61.000000  170.000000
national union         17.000000  56.000000  178.000000
none                    1.000000  57.000000  189.000000
republican             29.631579  55.263158  180.894737
whig                   11.000000  58.250000  176.000000


In [99]:
import pandas as pd
import numpy as np

presidents_df = pd.read_csv('https://sololearn.com/uploads/files/president_heights_party.csv', index_col='name')
                                  
print(presidents_df.groupby('party')['height'].agg(['min', np.median, max]))

                       min  median  max
party                                  
democratic             168     180  193
democratic-republican  163     177  189
federalist             170     170  170
national union         178     178  178
none                   189     189  189
republican             168     182  193
whig                   173     174  183


In [97]:
import pandas as pd
import numpy as np

presidents_df = pd.read_csv('https://sololearn.com/uploads/files/president_heights_party.csv', index_col='name')
                                  
print(presidents_df.groupby('party')\
    .agg({'height': [np.median, np.mean],
        'age':    [min, max]}))

                      height             age    
                      median        mean min max
party                                           
democratic               180  181.066667  43  65
democratic-republican    177  176.500000  57  58
federalist               170  170.000000  61  61
national union           178  178.000000  56  56
none                     189  189.000000  57  57
republican               182  180.894737  42  70
whig                     174  176.000000  50  68


## Test

Data Science - Reshape


Task
Given a list of numbers and the number of rows (r), reshape the list into a 2-dimensional array. Note that r divides the length of the list evenly.

Input Format
First line: an integer (r) indicating the number of rows of the 2-dimensional array
Next line: numbers separated by the space

Output Format
An numpy 2d array of values rounded to the second decimal.
```
Sample Input
2
1.2 0 0.5 -1

Sample Output
[[ 1.2 0. ]
[ 0.5 -1. ]]
```

In [121]:
import numpy as np

r = int(input()) 
lst = [float(x) for x in input().split()]
arr = np.array(lst)

n_col = len(arr)/r
print(n_col)

print(np.around(arr.reshape(r, int(n_col)),2))

3.0
[[6. 9. 8.]
 [3. 6. 9.]]
